### PR TITLE
Grunt setup

### PR DESCRIPTION
**Pull request by GLosch**
Grunt is up and running with HAML and SASS. No content yet

### CODE REVIEW

**Comment by brycemcd** [comment]
@GLosch do you plan on re-implementing `jshint` and `watch:js` in Gruntfile? If so, great. If not, remove the commented code. We can get it later if we really need it.

How'd it go pairing with @mkjenkins101 ?

**Comment by brycemcd** [comment]
oh, haha, k. Was more curious how the arrangement was working. Great we'll check in tonight

**Comment by GLosch** [comment]
Yep, just added it back in. I'd commented out a handful of components from the Gruntfile in hopes of determining the bare bones pieces. New pull request coming your way.

**Comment by brycemcd** [comment]
no need to do a new PR. Your push to this branch is :+1:

**Comment by GLosch** [comment]
Haha, yeah. Realized that right after I hit "comment"

**Pull request merged**
